casscore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^satellite/', include('satellite.urls')),
    url(r'^admin/', admin.site.urls),
]

satellite/urls.py
from django.conf.urls import url

from . import views

app_name = 'satellite'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'tm/$', views.tm, name='tm'),
    url(r'tm/errors$', views.errors, name='errors'),
    url(r'tm/hello$', views.hello, name='hello'),
    url(r'tm/housekeeping$', views.housekeeping, name='housekeeping'),
    url(r'tm/upload_tm$', views.upload_tm, name='upload_tm'),
]

satellite/models.py
from cassandra.cqlengine import columns
from django_cassandra_engine.models import DjangoCassandraModel


class EventErrComm(DjangoCassandraModel):
    # uid_ev = columns.TimeUUID(primary_key=True, default=uuid.uuid1)
    year = columns.Integer(primary_key=True, partition_key=True)
    post_time = columns.DateTime(primary_key=True, clustering_order="DESC")
    eve_name = columns.Text()
    mis_clock = columns.BigInt()
    seq_number = columns.Integer()

    class Meta:
        get_pk_field = 'post_time'

    def __str__(self):
        return "Error Event {} with clock {} and sequence {}.".format(self.eve_name, self.mis_clock, self.seq_number)


class HelloComm(DjangoCassandraModel):
    # uid_he = columns.TimeUUID(primary_key=True, default=uuid.uuid1)
    year = columns.Integer(primary_key=True, partition_key=True)
    post_time = columns.DateTime(primary_key=True, clustering_order="DESC")
    battery = columns.Text()
    boom1_vbus = columns.Text()
    boom2_vbus = columns.Text()
    mis_clock = columns.BigInt()
    mts_vbus = columns.Text()
    n15v_tm = columns.BigInt()
    ope_mode = columns.Text()
    p15v_tm = columns.BigInt()
    p3v3_tm = columns.BigInt()
    p5v_tm = columns.BigInt()
    rw_p5v = columns.Text()
    seq_number = columns.Integer()
    ttc_stat = columns.Text()

    class Meta:
        get_pk_field = 'post_time'

    def __str__(self):
        return "Hello Event, operating mode {} with clock {} and sequence {}.".format(self.ope_mode, self.mis_clock,
                                                                                      self.seq_number)


class HouseKeepComm(DjangoCassandraModel):
    # uid_hk = columns.TimeUUID(primary_key=True, default=uuid.uuid1)
    year = columns.Integer(primary_key=True, partition_key=True)
    post_time = columns.DateTime(primary_key=True, clustering_order="DESC")
    battery = columns.Text()
    boom1_vbus = columns.Text()
    boom2_vbus = columns.Text()
    mis_clock = columns.BigInt()
    mts_vbus = columns.Text()
    n15v_tm = columns.BigInt()
    ope_mode = columns.Text()
    p15v_tm = columns.BigInt()
    p3v3_tm = columns.BigInt()
    p5v_tm = columns.BigInt()
    rw_p5v = columns.Text()
    seq_number = columns.Integer()
    ttc_stat = columns.Text()

    class Meta:
        get_pk_field = 'post_time'

    def __str__(self):
        return "Housekeeping Event, operating mode {} with clock {} and sequence {}.".format(self.ope_mode,
                                                                                             self.mis_clock,
                                                                                             self.seq_number)


class Checksum(DjangoCassandraModel):
    checksum = columns.Text(primary_key=True)

satellite/views.py
# -*- coding: utf-8 -*-
import os
from django.utils import dateparse
from django.core.files.storage import FileSystemStorage
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render
from django.utils import timezone
from . import models
from tm_file_manager import TmFileManager
import pdb

NUM_OBJECTS_PAGE = 50


# Create your views here.
def index(request):
    return render(request, 'satellite/index.html')


def tm(request):
    return render(request, 'satellite/tm.html')


def errors(request):
    by_year, year = filter_by_year(request)
    by_time_from, time_from = filter_by_time(request, 'post_time_from')
    by_time_to, time_to = filter_by_time(request, 'post_time_to')
    error_list = None
    if by_year:
        error_list = models.EventErrComm.objects.filter(year__eq=year)
    if by_time_from:
        if error_list is None:
            error_list = models.EventErrComm.objects.filter(post_time__gte=time_from)
        else:
            error_list = error_list.filter(post_time__gte=time_from)
    if by_time_to:
        if error_list is None:
            error_list = models.EventErrComm.objects.filter(post_time__lte=time_to)
        else:
            error_list = error_list.filter(post_time__lte=time_to)
    if not by_year and not by_time_from and not by_time_to:
        error_list = models.EventErrComm.objects.all()
    paginator = Paginator(error_list, NUM_OBJECTS_PAGE)
    page = request.GET.get('page')
    try:
        e = paginator.page(page)
    except PageNotAnInteger:
        e = paginator.page(1)
    except EmptyPage:
        e = paginator.page(paginator.num_pages)
    return render(request, 'satellite/errors.html', {'info': e})


def hello(request):
    by_year, year = filter_by_year(request)
    by_time_from, time_from = filter_by_time(request, 'post_time_from')
    by_time_to, time_to = filter_by_time(request, 'post_time_to')
    hello_list = None
    if by_year:
        hello_list = models.HelloComm.objects.filter(year__eq=year)
    if by_time_from:
        if hello_list is None:
            hello_list = models.HelloComm.objects.filter(post_time__gte=time_from)
        else:
            hello_list = hello_list.filter(post_time__gte=time_from)
    if by_time_to:
        if hello_list is None:
            hello_list = models.HelloComm.objects.filter(post_time__lte=time_to)
        else:
            hello_list = hello_list.filter(post_time__lte=time_to)
    if not by_year and not by_time_from and not by_time_to:
        hello_list = models.HelloComm.objects.all()
    paginator = Paginator(hello_list, NUM_OBJECTS_PAGE)
    page = request.GET.get('page')
    try:
        e = paginator.page(page)
    except PageNotAnInteger:
        e = paginator.page(1)
    except EmptyPage:
        e = paginator.page(paginator.num_pages)
    return render(request, 'satellite/hello.html', {'info': e})


def housekeeping(request):
    by_year, year = filter_by_year(request)
    by_time_from, time_from = filter_by_time(request, 'post_time_from')
    by_time_to, time_to = filter_by_time(request, 'post_time_to')
    housek_list = None
    if by_year:
        housek_list = models.HouseKeepComm.objects.filter(year__eq=year)
    if by_time_from:
        if housek_list is None:
            housek_list = models.HouseKeepComm.objects.filter(post_time__gte=time_from)
        else:
            housek_list = housek_list.filter(post_time__gte=time_from)
    if by_time_to:
        if housek_list is None:
            housek_list = models.HouseKeepComm.objects.filter(post_time__lte=time_to)
        else:
            housek_list = housek_list.filter(post_time__lte=time_to)
    if not by_year and not by_time_from and not by_time_to:
        housek_list = models.HouseKeepComm.objects.all()
    paginator = Paginator(housek_list, NUM_OBJECTS_PAGE)
    page = request.GET.get('page')
    try:
        e = paginator.page(page)
    except PageNotAnInteger:
        e = paginator.page(1)
    except EmptyPage:
        e = paginator.page(paginator.num_pages)
    return render(request, 'satellite/housekeeping.html', {'info': e})


def upload_tm(request):
    msg = ""
    if request.method == 'POST' and request.FILES['tm_file']:
        tm_file = request.FILES['tm_file']
        file_name = os.path.splitext(tm_file.name)
        tm_file.name = file_name[0] + '.' + timezone.now().strftime("%d%b%Y_%H%M%S") + '.txt'
        fs = FileSystemStorage()
        fs.save(tm_file.name, tm_file)
        fm = TmFileManager()
        result = fm.process(os.path.join(fs.location, tm_file.name))
        msg = "File uploaded successfully!"
        if result == -1:
            msg = "File already uploaded!"
    return render(request, 'satellite/upload_tm.html', {'msg': msg})


def filter_by_year(request):
    try:
        year = int(request.GET.get('year'))
    except (ValueError, TypeError):
        return False, -1
    return True, year


def filter_by_time(request, param_name):
    try:
        time_ = dateparse.parse_datetime(request.GET.get(param_name))
        if time_ is None:
            return False, None
    except (ValueError, TypeError):
        return False, None
    return True, time_

satellite/templates/satellite/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TM</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

satellite/templates/satellite/errors.html
{% extends 'satellite/info.html' %}

{% block grid %}
<div style="margin-bottom: 20px;">
    <form action="{% url 'satellite:errors' %}" method="get">
        {% csrf_token %}
        <table>
            <tr>
                <td>Year =</td>
                <td><input type="text" name="year"></td>
            </tr>
            <tr>
                <td>Datetime from:</td>
                <td><input type="text" name="post_time_from"> (yyyy-mm-dd hh:mm:ss.ms)</td>
            </tr>
            <tr>
                <td>Datetime to:</td>
                <td><input type="text" name="post_time_to"> (yyyy-mm-dd hh:mm:ss.ms)</td>
            </tr>
        </table>
        <button type="submit">Filter</button>
        <button type="reset">Reset</button>
    </form>
</div>
<div style="margin-bottom: 20px;">
    <table>
        <thead>
        <tr>
            <th>Year</th>
            <th>Datetime</th>
            <th>Event Name</th>
            <th>Mission Clock</th>
            <th>Sequence Number</th>
        </tr>
        </thead>
        <tbody>
        {% for error in info %}
        <tr>
            <td>{{ error.year }}</td>
            <td>{{ error.post_time|date:"d-m" }} {{ error.post_time|time:"H:i:s.u" }}</td>
            <td>{{ error.eve_name }}</td>
            <td>{{ error.mis_clock }}</td>
            <td>{{ error.seq_number }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

satellite/templates/satellite/event_error.html
{% extends 'satellite/info.html' %}

{% block grid %}
<table>
	<thead>
	<tr>
		<th>Event Name</th>
		<th>Mission Clock</th>
		<th>Sequence Number</th>
	</tr>
	</thead>
	<tbody>
	{% for error in errors %}
	<tr>
		<td>{{ error.eve_name }}</td>
		<td>{{ error.mis_clock }}</td>
		<td>{{ error.seq_number }}</td>
	</tr>
	{% endfor %}
	</tbody>
</table>
{% endblock %}

satellite/templates/satellite/hello.html
{% extends 'satellite/info.html' %}

{% block grid %}
<div style="margin-bottom: 20px;">
    <form action="{% url 'satellite:hello' %}" method="get">
        {% csrf_token %}
        <table>
            <tr>
                <td>Year =</td>
                <td><input type="text" name="year"></td>
            </tr>
            <tr>
                <td>Datetime from:</td>
                <td><input type="text" name="post_time_from"> (yyyy-mm-dd hh:mm:ss.ms)</td>
            </tr>
            <tr>
                <td>Datetime to:</td>
                <td><input type="text" name="post_time_to"> (yyyy-mm-dd hh:mm:ss.ms)</td>
            </tr>
        </table>
        <button type="submit">Filter</button>
        <button type="reset">Reset</button>
    </form>
</div>
<div style="margin-bottom: 20px;">
    <table>
        <thead>
        <tr>
            <th>Year</th>
            <th>Datetime</th>
            <th>Battery</th>
            <th>BOOM1 VBUS</th>
            <th>BOOM2 VBUS</th>
            <th>Mission Clock</th>
            <th>MTS VBUS</th>
            <th>n15V TM</th>
            <th>Operating Mode</th>
            <th>p15V TM</th>
            <th>p3v3 TM</th>
            <th>p5v TM</th>
            <th>RW P5V</th>
            <th>Sequence Number</th>
            <th>TTC STAT</th>
        </tr>
        </thead>
        <tbody>
        {% for hello in info %}
        <tr>
            <td>{{ hello.year }}</td>
            <td>{{ hello.post_time|date:"d-m" }} {{ hello.post_time|time:"H:i:s.u" }}</td>
            <td>{{ hello.battery }}</td>
            <td>{{ hello.boom1_vbus}}</td>
            <td>{{ hello.boom2_vbus }}</td>
            <td>{{ hello.mis_clock }}</td>
            <td>{{ hello.mts_vbus }}</td>
            <td>{{ hello.n15v_tm }}</td>
            <td>{{ hello.ope_mode }}</td>
            <td>{{ hello.p15v_tm }}</td>
            <td>{{ hello.p3v3_tm }}</td>
            <td>{{ hello.p5v_tm }}</td>
            <td>{{ hello.rw_p5v }}</td>
            <td>{{ hello.seq_number }}</td>
            <td>{{ hello.ttc_stat }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

satellite/templates/satellite/housekeeping.html
{% extends 'satellite/info.html' %}

{% block grid %}
<div style="margin-bottom: 20px;">
    <form action="{% url 'satellite:housekeeping' %}" method="get">
        {% csrf_token %}
        <table>
            <tr>
                <td>Year =</td>
                <td><input type="text" name="year"></td>
            </tr>
            <tr>
                <td>Datetime from:</td>
                <td><input type="text" name="post_time_from"> (yyyy-mm-dd hh:mm:ss.ms)</td>
            </tr>
            <tr>
                <td>Datetime to:</td>
                <td><input type="text" name="post_time_to"> (yyyy-mm-dd hh:mm:ss.ms)</td>
            </tr>
        </table>
        <button type="submit">Filter</button>
        <button type="reset">Reset</button>
    </form>
</div>
<div style="margin-bottom: 20px;">
    <table>
        <thead>
        <tr>
            <th>Year</th>
            <th>Datetime</th>
            <th>Battery</th>
            <th>BOOM1 VBUS</th>
            <th>BOOM2 VBUS</th>
            <th>Mission Clock</th>
            <th>MTS VBUS</th>
            <th>n15V TM</th>
            <th>Operating Mode</th>
            <th>p15V TM</th>
            <th>p3v3 TM</th>
            <th>p5v TM</th>
            <th>RW P5V</th>
            <th>Sequence Number</th>
            <th>TTC STAT</th>
        </tr>
        </thead>
        <tbody>
        {% for housek in info %}
        <tr>
            <td>{{ housek.year }}</td>
            <td>{{ housek.post_time|date:"d-m" }} {{ housek.post_time|time:"H:i:s.u" }}</td>
            <td>{{ housek.battery }}</td>
            <td>{{ housek.boom1_vbus}}</td>
            <td>{{ housek.boom2_vbus }}</td>
            <td>{{ housek.mis_clock }}</td>
            <td>{{ housek.mts_vbus }}</td>
            <td>{{ housek.n15v_tm }}</td>
            <td>{{ housek.ope_mode }}</td>
            <td>{{ housek.p15v_tm }}</td>
            <td>{{ housek.p3v3_tm }}</td>
            <td>{{ housek.p5v_tm }}</td>
            <td>{{ housek.rw_p5v }}</td>
            <td>{{ housek.seq_number }}</td>
            <td>{{ housek.ttc_stat }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

satellite/templates/satellite/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Satellite UPM-SAT2</title>
</head>
<body>
    <div>
        <a href="{% url 'satellite:tm' %}">TM</a>
        <br />
        <a href="#">TC</a>
        <br />
    </div>
</body>
</html>

satellite/templates/satellite/info.html
{% extends 'satellite/base.html' %}

{% block content %}
<div style="margin-bottom: 20px;"><a href="{% url 'satellite:tm' %}">Back</a></div>
{% block grid %}
{% endblock %}
<div class="pagination">
	<span class="step-links">
		{% if info.has_previous %}
			<a href="?page={{ info.previous_page_number }}">previous</a>
		{% endif %}

		<span class="current">
			Page {{ info.number }} of {{ info.paginator.num_pages }}.
		</span>

		{% if info.has_next %}
			<a href="?page={{ info.next_page_number }}">next</a>
		{% endif %}
	</span>
</div>
{% endblock %}

satellite/templates/satellite/tm.html
{% extends 'satellite/base.html' %}

{% block content %}
<div style="margin-bottom: 20px;"><a href="{% url 'satellite:index' %}">Back</a></div>
<div style="margin-bottom: 20px;">
    <a href="{% url 'satellite:errors' %}">Event Error</a>
    <br />
    <a href="{% url 'satellite:hello' %}">Hello</a>
    <br />
    <a href="{% url 'satellite:housekeeping' %}">Housekeeping</a>
    <br />
</div>
<div style="margin-bottom: 20px;"><a href="{% url 'satellite:upload_tm' %}">Upload File</a></div>
{% endblock %}

satellite/templates/satellite/upload_tm.html
{% extends 'satellite/base.html' %}

{% block content %}
<div style="margin-bottom: 20px;"><a href="{% url 'satellite:tm' %}">Back</a></div>
<div style="margin-bottom: 20px;">
<form action="{% url 'satellite:upload_tm' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="tm_file">
    <button type="submit">Upload</button>
</form>
</div>
<div>{{ msg }}</div>
{% endblock %}